// flow-typed signature: ea90b1163641d5be17ef270169f490e8
// flow-typed version: <<STUB>>/ordinal_v1.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ordinal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ordinal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ordinal/indicator' {
  declare module.exports: any;
}

declare module 'ordinal/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ordinal/index' {
  declare module.exports: $Exports<'ordinal'>;
}
declare module 'ordinal/index.js' {
  declare module.exports: $Exports<'ordinal'>;
}
declare module 'ordinal/indicator.js' {
  declare module.exports: $Exports<'ordinal/indicator'>;
}
declare module 'ordinal/test/index.js' {
  declare module.exports: $Exports<'ordinal/test/index'>;
}
